[package]
name = "rust_boy"
version = "0.1.0"
authors = ["Alexander Wendt <alexwgh1+rustboy@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simplelog = { git = "https://github.com/AlexW-GH/simplelog.rs" }
image = "0.20"
