[package]
name = "rust_boy"
version = "0.1.0"
authors = ["Alex <mithnar333@googlemail.com>"]

[dependencies]
clap = "2.32"
log = "0.4"
simplelog = { git = "https://github.com/AlexW-GH/simplelog.rs" }
chrono = "0.4"
piston_window = "0.82"
image = "0.20"
piston-texture = "0.6"